[package]
name = "princeps_mathematicarum_imaginum"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
filters = { version = "0.1.0", path = "src/filters" }
image_processing = { version = "0.1.0", path = "src/image_processing" }
